baseURL = "https://lyyl80.github.io/"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
title = "lyyl80"
[pagination]
  pagerSize = 10

[params]
  env = "production"
  description = "写代码，也写生活。"
  author = "lyyl80"
  tagline = "写代码，也写生活。"
  github = "lyyl80"
  email = ""

[params.assets]
  favicon = "/favicon.ico"

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    guessSyntax = true

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 4

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5
